apiVersion: v2
appVersion: "1.0"
description: A Helm chart for da-cos-api App
name: da-cos-api
home: https://github.com/hmcts/da-cos-api
version: 0.0.3
maintainers:
  - name: HMCTS Domestic Abuse team
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
  - name: ccd
    version: 6.0.0
    repository: '@hmctspublic'
    tags:
      - ccd-idam-pr
  - name: xui-webapp
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: xui-webapp.enabled
