tags:
  ccd-idam-pr: false

xui-webapp:
  enabled: false

idam-pr:
  enabled: false

java:
  image: 'hmctspublic.azurecr.io/da/cos-api:latest'
  ingressHost: da-cos-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4550
  aadIdentityName: da
  autoscaling:
    enabled: true
    maxReplicas: 9
    minReplicas: 6
    targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
  keyVaults:
    rpe:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
          keyVaults:
            da:
              secrets:
                - name: AppInsightsInstrumentationKey
                  alias: APP_INSIGHTS_KEY
                - name: s2s-cos-api-secret
                  alias: S2S_SECRET
                - name: idam-client-secret
                  alias: IDAM_CLIENT_SECRET
                - name: idam-systemupdate-username
                  alias: IDAM_SYSTEM_UPDATE_USERNAME
                - name: idam-systemupdate-password
                  alias: IDAM_SYSTEM_UPDATE_PASSWORD
  environment:
    REFORM_TEAM: da
    REFORM_SERVICE_NAME: da-cos-api
    REFORM_ENVIRONMENT: preview
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CASE_DATA_STORE_BASEURL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_API_REDIRECT_URL: https://da-cos-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/authenticated
    IDAM_API_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
